### ISSUE TITLE
Incorrect parsing of items

### ISSUE THREAD

**Issue by SchumacherFM** [bennyguitar/News-YC---iPhone#34]
hey,

every time I open the app in the last couple of days I always get this view:

![img_2207](https://cloud.githubusercontent.com/assets/372027/6311007/e6b1ad32-b9b0-11e4-8859-e52ca450ff7b.PNG)

It's the latest release from the apple app store.

The view of HN Jobs is always the same no matter what topic (New, Top, Ask) I select.

Am I doing something wrong? 8-)

**Comment by DRosadoYew** [comment]
Probably HN changed the website again and the scrapper doesn't like it. You'll have to wait for an updated release on the App Store.
 
However, from what i got from the latest commits in [libHN](https://github.com/bennyguitar/libHN) this should be solved already and quicker to fix next time (i.e. no App Store submission needed).

**Comment by bennyguitar** [comment]
New update will be submitted today. Thanks for being patient!

**Comment by SchumacherFM** [comment]
Update arrived today  :tada: ! Thank you very much! :+1:

**Comment by bennyguitar** [comment]
No problem, glad you like it!
